# Generated by Django 5.2.3 on 2026-01-14 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_lead_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='school',
            new_name='customer_type',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='email',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='phone',
        ),
        migrations.AddField(
            model_name='lead',
            name='governorate',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='order',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='order_type',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
